import type { Metadata } from "next";
import { Inter,Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar/navbar";
import TopHeader from "./components/topheader/topheader";
import Footer from "./components/footer/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const popins = Poppins({
  subsets: ["latin"],
  weight: ["400","700"]

}); 




export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={popins.className}>
        <TopHeader />
        <Navbar />
        <Footer />

        {children}</body>
      
    </html>
  );
}
